#!/usr/bin/env python3
"""Keep the topic `choice` dropdowns in the workflow YAMLs in sync with topics/.

GitHub Actions `workflow_dispatch` `choice` inputs must be hardcoded in the
YAML — they cannot be populated from the topics/ folder at runtime. This script
is the "dynamic" part: it reads the available topics (every folder under topics/
that has a config.yml, via scripts/topic.py:list_topics) and rewrites the option
list inside each marked block in the workflows.

A managed block looks like:

    options:
      # >>> topic-options (generated by scripts/sync_topic_choices.py — do not edit by hand)
      - ai_data_centers
      - ...
      # <<< topic-options

Add `extra=<comma,separated>` to the begin marker to prepend fixed options
(e.g. `extra=all` for the collect-samples filter, where "all" means no filter):

    # >>> topic-options extra=all (generated by scripts/sync_topic_choices.py — do not edit by hand)

Usage:
    python scripts/sync_topic_choices.py          # rewrite the workflows in place
    python scripts/sync_topic_choices.py --check   # exit 1 if anything is stale (for CI)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from topic import list_topics  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
WORKFLOWS_DIR = REPO_ROOT / ".github" / "workflows"

BEGIN_RE = re.compile(
    r"^(?P<indent>\s*)#\s*>>>\s*topic-options(?:\s+extra=(?P<extra>\S+))?.*$"
)
END_RE = re.compile(r"^\s*#\s*<<<\s*topic-options.*$")


def render_block(indent: str, extra: str | None, topics: list[str]) -> list[str]:
    """Build the option lines (without the marker lines) for one block."""
    names: list[str] = []
    if extra:
        names.extend(e for e in extra.split(",") if e)
    names.extend(topics)
    return [f"{indent}- {name}" for name in names]


def sync_text(text: str, topics: list[str]) -> str:
    lines = text.splitlines(keepends=True)
    out: list[str] = []
    i = 0
    while i < len(lines):
        m = BEGIN_RE.match(lines[i].rstrip("\n"))
        if not m:
            out.append(lines[i])
            i += 1
            continue

        # Keep the begin marker, swap the body, keep the end marker.
        out.append(lines[i])
        indent = m.group("indent")
        extra = m.group("extra")
        nl = "\n"

        j = i + 1
        while j < len(lines) and not END_RE.match(lines[j].rstrip("\n")):
            j += 1
        if j >= len(lines):
            raise SystemExit(
                "Unterminated '# >>> topic-options' block (missing "
                "'# <<< topic-options')."
            )

        for line in render_block(indent, extra, topics):
            out.append(line + nl)
        out.append(lines[j])  # the end marker
        i = j + 1

    return "".join(out)


def main() -> int:
    check = "--check" in sys.argv[1:]
    topics = list_topics()
    if not topics:
        raise SystemExit("No topics found under topics/ — refusing to wipe dropdowns.")

    stale: list[Path] = []
    for wf in sorted(WORKFLOWS_DIR.glob("*.yml")):
        original = wf.read_text(encoding="utf-8")
        if "topic-options" not in original:
            continue
        updated = sync_text(original, topics)
        if updated == original:
            continue
        stale.append(wf)
        if not check:
            wf.write_text(updated, encoding="utf-8")

    if check:
        if stale:
            print("Topic dropdowns are out of sync. Run scripts/sync_topic_choices.py:")
            for wf in stale:
                print(f"  - {wf.relative_to(REPO_ROOT)}")
            return 1
        print("Topic dropdowns are in sync.")
        return 0

    if stale:
        for wf in stale:
            print(f"Updated {wf.relative_to(REPO_ROOT)}")
    else:
        print("Topic dropdowns already in sync.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
